#include <stdlib.h>
#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

#include "log.h"

#include <stdlib.h>

// initialize ip header
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	u32 max_mask = 0;
	rt_entry_t *the_entry = NULL;
	rt_entry_t *entry = NULL;
	u32 net;
	list_for_each_entry(entry, &rtable, list){
// initialize ip header""
	net = entry->dest & entry->mask;
	
        if((dst & entry->mask) == net && entry->mask > max_mask){
	fprintf(stderr, "mask:");
		fprintf(stderr, IP_FMT,LE_IP_FMT_STR(entry->mask));
	fprintf(stderr, "net:");
	fprintf(stderr, IP_FMT,LE_IP_FMT_STR(net));
            the_entry = entry;
            max_mask = entry->mask;
        }
	}
	return the_entry;
}

// forward the IP packet from the interface specified by longest_prefix_match,
// when forwarding the packet, you should check the TTL, update the checksum,
// determine the next hop to forward the packet, then send the packet by
// iface_send_packet_by_arp
void ip_forward_packet(u32 ip_dst, char *packet, int len)
{
	fprintf(stderr, "TODO: forward ip packet.\n");
	struct iphdr *ip = packet_to_ip_hdr(packet);
	rt_entry_t *entry = longest_prefix_match(ip_dst);
	if(!entry){
        //int icmp_len = ETHER_HDR_SIZE + 2 *IP_HDR_SIZE(ip) + 2*ICMP_COPIED_DATA_LEN;
        //char *icmp_packet = malloc(icmp_len);
        //memcpy(icmp_packet,packet,ETHER_HDR_SIZE + IP_HDR_SIZE(ip) + ICMP_COPIED_DATA_LEN);
        icmp_send_packet(packet,len,ICMP_DEST_UNREACH,ICMP_NET_UNREACH);
	}
	else{
        if(ip->ttl == 0){
            int icmp_len = ETHER_HDR_SIZE + 2 *IP_HDR_SIZE(ip) + 2*ICMP_COPIED_DATA_LEN;
            char *icmp_packet = malloc(icmp_len);
            memcpy(icmp_packet,packet,ETHER_HDR_SIZE + IP_HDR_SIZE(ip) + ICMP_COPIED_DATA_LEN);
            icmp_send_packet(icmp_packet,icmp_len,ICMP_TIME_EXCEEDED,0);
        }
        else{
            ip->ttl = (ip->ttl)--;
            ip->checksum = ip_checksum(ip);
            u32 next_hop = entry->gw;
            if (!next_hop)
                next_hop = ip_dst;

            struct ether_header *eh = (struct ether_header *)packet;
            memcpy(eh->ether_shost, entry->iface->mac, ETH_ALEN);

            iface_send_packet_by_arp(entry->iface, next_hop, packet, len);
        }
	}
}

// handle ip packet
//
// If the packet is ICMP echo request and the destination IP address is equal to
// the IP address of the iface, send ICMP echo reply; otherwise, forward the
// packet.
void handle_ip_packet(iface_info_t *iface, char *packet, int len)
{
	fprintf(stderr, "TODO: handle ip packet: echo the ping packet, and forward other IP packets.\n");

    struct iphdr *ip_hdr = packet_to_ip_hdr(packet);
    u32 dst = ntohl(ip_hdr->daddr);
	u32 src = ntohl(ip_hdr->saddr);
	if(ip_hdr->protocol == IPPROTO_ICMP && dst == iface->ip){
        ip_init_hdr(ip_hdr,iface->ip,ntohl(ip_hdr->saddr),len-ETHER_HDR_SIZE,IPPROTO_ICMP);
	fprintf(stderr, IP_FMT,LE_IP_FMT_STR(src));
        icmp_send_packet(packet, len, 0, 0);
	}
	else{
        ip_forward_packet(dst, packet, len);
	}
}

// send IP packet
//
// Different from ip_forward_packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	struct iphdr *ip = packet_to_ip_hdr(packet);
	u32 dst = ntohl(ip->daddr);
	rt_entry_t *entry = longest_prefix_match(dst);
	if (!entry) {
		log(ERROR, "Could not find forwarding rule for IP (dst:"IP_FMT") packet.",
				HOST_IP_FMT_STR(dst));
		free(packet);
		return ;
	}

	u32 next_hop = entry->gw;
	if (!next_hop)
		next_hop = dst;
	fprintf(stderr, IP_FMT,LE_IP_FMT_STR(dst));
	fprintf(stderr, IP_FMT,LE_IP_FMT_STR(next_hop));
	struct ether_header *eh = (struct ether_header *)packet;
	eh->ether_type = htons(ETH_P_IP);
	memcpy(eh->ether_shost, entry->iface->mac, ETH_ALEN);
	//ip->saddr = htonl(entry->iface->ip);
	iface_send_packet_by_arp(entry->iface, next_hop, packet, len);
}
